# tier_scaling_config.toml

[global]
tiers_enabled = true  # Enables or disables the tier system

[tier_linearization]
# Format: tier_number = level
1 = 10
2 = 16
3 = 25
4 = 35
5 = 50

[mob_tiers]
# Format: "mod_id:entity_id" = tier_number
"minecraft:zombie" = 1
"minecraft:skeleton" = 2
"minecraft:creeper" = 3
"minecraft:spider" = 2
"modid:custom_mob" = 4  # Example for a custom mob from another mod

[item_tiers]
# Format: "mod_id:item_id" = tier_number
"minecraft:wooden_sword" = 1
"minecraft:stone_sword" = 2
"minecraft:iron_sword" = 3
"minecraft:diamond_sword" = 4
"modid:custom_sword" = 5  # Example for a custom item from another mod
